[profile.default]
src          = "src"
script       = "script"
out          = "out"
libs         = ["../contracts/lib"]
allow_paths  = ["../contracts/src"]
solc         = "0.8.28"
via_ir       = true
optimizer    = true
optimizer_runs = 200
