[workspace]
members = [
    "crates/wormhole-sdk",
    "crates/wormhole-cli",
]
resolver = "2"

[workspace.dependencies]
tokio       = { version = "1", features = ["full"] }
anyhow      = "1"
thiserror   = "1"
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
hex         = "0.4"
base64      = "0.22"
sha3        = "0.10"
k256        = { version = "0.13", features = ["ecdsa"] }
reqwest     = { version = "0.12", features = ["json"] }
async-trait = "0.1"
bs58        = "0.5"
rlp         = "0.5"
